<template>
<div>

<b>Last Revised: April 9th, 2018</b>
<p>
The following terms and conditions (the “Terms of Service” or “Agreement”) constitutes the entire agreement between you (“User”, “You” or “Your”) and Cryptoscout LLC, a Limited Liability Company registered in the State of Nevada (“Cryptoscout LLC”, “The Company“, “Us”, “Our”, or ‘We”).
</p>
<p>
These terms may be updated at anytime and will be updated on this page.
</p><br>


<b>Links</b>
<p>
The Website may contain links, including payment links, to other websites and/or advertisements that take a user to another website. The Company does not endorse and is not responsible for the content, Terms of Service, or privacy policies of any such websites. Any use of these other websites is at Your sole risk.
</p><br>

<b>General Disclosures</b>
<p>
Research or information on the Website is not an offer to sell or the solicitation of an offer to buy any security or cryptocurrency in any jurisdiction where such an offer or solicitation would be illegal. It does not constitute a personal recommendation to You or take into account the particular investment objectives, financial situations, or needs of individual users. You should consider whether any perceived advice or recommendation in this research or information is suitable for Your particular circumstances and, if appropriate, seek professional advice, including tax or legal advice.
</p><br>

<b>NO WARRANTIES/DISCLAIMERS</b>
<p>
THE SERVICES AND WEBSITE ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. YOUR USE OF THE SERVICES AND WEBSITE IS AT YOUR SOLE RISK. THE COMPANY MAKES NO WARRANTIES ABOUT THE ACCURACY, RELIABILITY, COMPLETENESS OR TIMELINESS OF THE SERVICES OFFERED OR ANY OTHER CONTENT ACCESSED THROUGH THE WEBSITE.<br>
THE COMPANY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTY OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE AND NON-INFRINGEMENT.<br>
THE COMPANY DOES NOT WARRANT THAT THE WEBSITE WILL OPERATE ERROR-FREE OR THAT THE WEBSITE IS FREE OF COMPUTER VIRUSES OR OTHER HARMFUL MECHANISMS. THE COMPANY IS NOT RESPONSIBLE FOR COSTS ASSOCIATED WITH THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA.<br>
ALTHOUGH THE INTENT IS TO PROVIDE ACCURATE AND TIMELY INFORMATION, THE CONTENT AND INFORMATION PROVIDED MAY NOT ALWAYS BE ENTIRELY ACCURATE, COMPLETE OR CURRENT AND MAY ALSO INCLUDE TECHNICAL INACCURACIES OR TYPOGRAPHICAL ERRORS. CONTENT INFORMATION MAY BE CHANGED OR UPDATED FROM TIME TO TIME WITHOUT NOTICE, INCLUDING WITHOUT LIMITATION INFORMATION REGARDING OUR POLICIES, PRODUCTS AND SERVICES. ACCORDINGLY, YOU SHOULD VERIFY ALL INFORMATION BEFORE RELYING ON IT, IF AT ALL, AND ALL DECISIONS BASED ON INFORMATION CONTAINED ON THE WEBSITE ARE YOUR SOLE RESPONSIBILITY AND THE COMPANY SHALL HAVE NO LIABILITY FOR SUCH DECISIONS. LINKS TO THIRD-PARTY MATERIALS (INCLUDING WITHOUT LIMITATION WEBSITES) MAY BE PROVIDED AS A CONVENIENCE BUT ARE NOT CONTROLLED BY US. YOU ACKNOWLEDGE AND AGREE THAT WE ARE NOT RESPONSIBLE FOR ANY ASPECT OF THE INFORMATION, CONTENT, OR SERVICES CONTAINED IN ANY THIRD-PARTY MATERIALS OR ON ANY THIRD-PARTY SITES ACCESSIBLE OR LINKED TO THE WEBSITE.<br>
THE TRANSMISSION OF DATA OR INFORMATION INCLUDING COMMUNICATIONS BY E-MAIL OVER THE INTERNET OR OTHER PUBLICLY ACCESSIBLE NETWORKS IS NOT SECURE, AND IS SUBJECT TO POSSIBLE LOSS, INTERCEPTION OR ALTERATION WHILE IN TRANSIT. ACCORDINGLY, THE COMPANY DOES NOT ASSUME ANY LIABILITY FOR ANY DAMAGE YOU MAY EXPERIENCE OR COSTS YOU MAY INCUR AS A RESULT OF ANY TRANSMISSIONS OVER THE INTERNET OR OTHER PUBLICLY ACCESSIBLE NETWORKS, SUCH AS TRANSMISSIONS INVOLVING THE EXCHANGE OF E-MAIL. WHILE THE COMPANY TAKES COMMERCIALLY REASONABLE EFFORTS TO SAFEGUARD THE PRIVACY OF THE INFORMATION YOU PROVIDE AND TREAT SUCH INFORMATION IN ACCORDANCE WITH OUR PRIVACY POLICY, IN NO EVENT WILL THE INFORMATION YOU PROVIDE BE DEEMED TO BE CONFIDENTIAL, CREATE ANY FIDUCIARY OBLIGATIONS ON THE COMPANY’S PART, OR RESULT IN ANY LIABILITY TO YOU IN THE EVENT THAT SUCH INFORMATION IS INADVERTENTLY RELEASED BY US OR ACCESSED BY THIRD PARTIES WITHOUT CONSENT.<br>
THE COMPANY TAKES NO RESPONSIBILITY WHATSOEVER FOR THE INFORMATION YOU HAVE UPLOADED TO THE WEBSITE AND SHALL NOT BE RESPONSIBLE OR LIABLE FOR THE DELETION, CORRECTION, DESTRUCTION, DAMAGE, OR LOSS OF SUCH INFORMATION, OR FAILURE TO STORE ANY OF SUCH INFORMATION. NOR IS THE COMPANY RESPONSIBLE FOR LOSS OF INFORMATION THROUGH THE ACTION OF ANY THIRD PARTY OR BECAUSE OF CIRCUMSTANCES BEYOND THE COMPANY’S CONTROL. ALL USERS ARE EXPECTED TO HAVE THEIR OWN BACKUP OF ALL OF THEIR INFORMATION.
</p><br>

<b>LIMITATION OF LIABILITY</b>
<p>
IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE D1542, WHICH SAYS: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR."<br>
IN ADDITION TO ANY LIMITATION OF LIABILITY SET FORTH HEREIN, TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, YOU HEREBY UNDERSTAND AND AGREE THAT NEITHER THE COMPANY NOR ITS SUBSIDIARIES, AFFILIATES, PARTNERS, OFFICERS, DIRECTORS, EMPLOYEES, REPRESENTATIVES OR AGENTS SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY OR ANY OTHER DAMAGES RELATING TO OR RESULTING FROM YOUR USE OR INABILITY TO USE THE WEBSITE OR ACCESS THE SERVICES OR FROM ANY ACTIONS THE COMPANY TAKES OR FAILS TO TAKE, WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THESE INCLUDE DAMAGES FOR ERRORS, OMISSIONS, INTERRUPTIONS, DEFECTS, DELAYS, COMPUTER VIRUSES, LOSS OF PROFITS, LOSS OF DATA, UNAUTHORIZED ACCESS TO AND ALTERATION OF TRANSMISSIONS AND DATA, BODILY INJURY, EMOTIONAL DISTRESS AND OTHER TANGIBLE AND INTANGIBLE LOSSES.
THIS LIMITATION APPLIES REGARDLESS OF WHETHER THE DAMAGES ARE CLAIMED UNDER THE TERMS OF A CONTRACT, AS THE RESULT OF NEGLIGENCE OR OTHERWISE, AND EVEN IF WE OR OUR REPRESENTATIVES HAVE BEEN NEGLIGENT OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. COMPANY'S MAXIMUM LIABILITY ARISING OUT OF OR IN CONNECTION WITH THIS WEBSITE OR YOUR USE OF THE SERVICES, REGARDLESS OF THE CAUSE OF ACTION (WHETHER IN CONTRACT, TORT, BREACH OF WARRANTY OR OTHERWISE), WILL NOT EXCEED THE AMOUNT, IF ANY, PAID BY YOU FOR THE SERVICES.
</p><br>

<b>YOUR LIABILITY</b>
<p>
IF YOU CAUSE A TECHNICAL DISRUPTION TO THE SERVICES OR TO OTHERS YOU AGREE TO BE RESPONSIBLE FOR ANY AND ALL LIABILITIES, COSTS AND EXPENSES (INCLUDING ATTORNEY'S FEES) ARISING FROM THAT DISRUPTION.
YOU HEREBY AGREE TO DEFEND, INDEMNIFY, AND HOLD HARMLESS THE COMPANY AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, REPRESENTATIVES, AND PARTNERS, HARMLESS FROM AND AGAINST ANY LOSS, LIABILITY, CLAIM, ACTION, OR DEMAND, INCLUDING WITHOUT LIMITATION REASONABLE LEGAL AND ACCOUNTING FEES, ALLEGING OR RESULTING FROM (I) YOUR USE OF THE SERVICES; (II) ANY MATERIAL YOU PROVIDE TO THE SERVICES, (III) ANY SERVICES THAT YOU USE OR (IV) YOUR BREACH OF THE TERMS OF THIS AGREEMENT AND YOUR REPRESENTATIONS AND WARRANTIES. THE COMPANY SHALL PROVIDE NOTICE TO YOU PROMPTLY OF ANY SUCH CLAIM, SUIT, OR PROCEEDING AND SHALL ASSIST YOU, AT YOUR EXPENSE, IN DEFENDING ANY SUCH CLAIM, SUIT OR PROCEEDING. THE COMPANY RESERVES THE RIGHT TO ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER SUBJECT TO IMMEDIATE INDEMNIFICATION BY YOU.
</p><br>



<b>Registered Users and Email List</b>
<p>
By signing up to our service, you agree to enroll in our mailing list and newsletter. The Company uses the mailing list to disseminate content along with important news and information about Our services. The Terms of Service for Our products and services apply to the mailing as well.
</p><br>

</div>
</template>

<style scoped>
    b{
        font-size: 16px;
    }
    p {
        margin-top: 7px;
    }
</style>
